spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oppo?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: a123456@
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    port: 6379
#    host: 127.0.0.1
#  profiles:
#    active: prod

mybatis:
  mapper-locations: classpath:Mapper/*Mapper.xml # mapper映射文件路径
  type-aliases-package: com.example.diet.Domain   # 配置哪个包下的类有默认的别名

server:
  port: 80

#debug: false
#
#logging:
#  level:
#    com.example.diet: debug
